from __future__ import annotations

import tkinter as tk
from tkinter import messagebox, ttk
from typing import Any

from Grocery_Sense.services.price_drop_alert_service import PriceDropAlertService


def open_price_drop_alerts_window(app, log=None) -> None:
    PriceDropAlertsWindow(app, log=log)


class PriceDropAlertsWindow(tk.Toplevel):
    """
    Milestone 2 UI:
      - Shows alerts generated by PriceDropAlertService (usual price + 6-mo low + staple logic)
      - Supports dismissing alerts (suppresses re-creation for ~30 days)
      - Optionally supports scanning recent receipts to detect "paid below usual"
    """

    def __init__(self, app, log=None) -> None:
        super().__init__(app.root)
        self.app = app
        self._log = log
        self.title("Price Drop Alerts")
        self.geometry("1100x620")

        self.svc = PriceDropAlertService(log=log)
        self._staples_only = tk.BooleanVar(value=True)

        self._build_ui()
        self._refresh()

    def _build_ui(self) -> None:
        top = ttk.Frame(self)
        top.pack(fill="x", padx=10, pady=(10, 6))

        ttk.Checkbutton(
            top,
            text="Staples only (recommended)",
            variable=self._staples_only,
            command=self._refresh,
        ).pack(side="left")

        ttk.Button(top, text="Refresh Alerts", command=self._refresh).pack(side="left", padx=(10, 0))
        ttk.Button(top, text="Scan Recent Receipts", command=self._scan_receipts).pack(side="left", padx=(10, 0))
        ttk.Button(top, text="Dismiss Selected", command=self._dismiss_selected).pack(side="left", padx=(10, 0))
        ttk.Button(top, text="Close", command=self.destroy).pack(side="right")

        mid = ttk.Frame(self)
        mid.pack(fill="both", expand=True, padx=10, pady=6)

        cols = (
            "item_name",
            "store_name",
            "alert_kind",
            "current_price",
            "usual_price",
            "pct_below_usual",
            "six_month_low",
            "pct_above_low",
            "is_staple",
            "receipt_samples",
            "source",
            "created_at",
        )

        self.tree = ttk.Treeview(mid, columns=cols, show="headings", selectmode="browse", height=16)
        self.tree.pack(side="left", fill="both", expand=True)

        vsb = ttk.Scrollbar(mid, orient="vertical", command=self.tree.yview)
        vsb.pack(side="right", fill="y")
        self.tree.configure(yscrollcommand=vsb.set)

        self.tree.heading("item_name", text="Item")
        self.tree.heading("store_name", text="Best Store")
        self.tree.heading("alert_kind", text="Alert")
        self.tree.heading("current_price", text="Current")
        self.tree.heading("usual_price", text="Usual")
        self.tree.heading("pct_below_usual", text="% Below Usual")
        self.tree.heading("six_month_low", text="6-mo Low")
        self.tree.heading("pct_above_low", text="% Above Low")
        self.tree.heading("is_staple", text="Staple")
        self.tree.heading("receipt_samples", text="Receipt Samples")
        self.tree.heading("source", text="Source")
        self.tree.heading("created_at", text="Created")

        self.tree.column("item_name", width=230, anchor="w")
        self.tree.column("store_name", width=140, anchor="w")
        self.tree.column("alert_kind", width=110, anchor="center")
        self.tree.column("current_price", width=90, anchor="e")
        self.tree.column("usual_price", width=90, anchor="e")
        self.tree.column("pct_below_usual", width=105, anchor="e")
        self.tree.column("six_month_low", width=90, anchor="e")
        self.tree.column("pct_above_low", width=95, anchor="e")
        self.tree.column("is_staple", width=70, anchor="center")
        self.tree.column("receipt_samples", width=110, anchor="center")
        self.tree.column("source", width=90, anchor="center")
        self.tree.column("created_at", width=150, anchor="w")

        self.tree.bind("<<TreeviewSelect>>", self._on_select)

        bottom = ttk.LabelFrame(self, text="Why this alert?")
        bottom.pack(fill="both", expand=False, padx=10, pady=(0, 10))

        self.details = tk.Text(bottom, height=7, wrap="word")
        self.details.pack(fill="both", expand=True, padx=8, pady=8)
        self.details.configure(state="disabled")

    def _refresh(self) -> None:
        try:
            self.svc.refresh_engine_alerts(staples_only=self._staples_only.get())
            alerts = self.svc.get_open_alerts()
        except Exception as e:
            messagebox.showerror("Error", f"Failed to load alerts:\n{e}")
            return

        for row in self.tree.get_children():
            self.tree.delete(row)

        for a in alerts:
            iid = a.get("id")
            values = (
                a.get("item_name") or "",
                a.get("store_name") or "",
                (a.get("alert_kind") or "").replace("_", " ").title(),
                self._fmt_money(a.get("current_price")),
                self._fmt_money(a.get("usual_price")),
                self._fmt_pct(a.get("pct_below_usual")),
                self._fmt_money(a.get("six_month_low")),
                self._fmt_pct(a.get("pct_above_low")),
                "Yes" if int(a.get("is_staple") or 0) == 1 else "No",
                str(a.get("receipt_samples") or 0),
                a.get("source") or "",
                (a.get("created_at") or "")[:19].replace("T", " "),
            )
            self.tree.insert("", "end", iid=str(iid), values=values)

        self._set_details("Select an alert to see the explanation.")

    def _scan_receipts(self) -> None:
        try:
            inserted = self.svc.scan_recent_receipts(days=21)
            self._refresh()
            messagebox.showinfo("Scan complete", f"Created {inserted} new receipt-based alerts (if any).")
        except Exception as e:
            messagebox.showerror("Error", f"Scan failed:\n{e}")

    def _dismiss_selected(self) -> None:
        sel = self.tree.selection()
        if not sel:
            messagebox.showinfo("Dismiss", "Select an alert first.")
            return

        alert_id = int(sel[0])
        if not messagebox.askyesno("Dismiss alert", "Dismiss this alert? (It won't reappear for ~30 days)"):
            return

        try:
            self.svc.dismiss_alert(alert_id)
            self._refresh()
        except Exception as e:
            messagebox.showerror("Error", f"Dismiss failed:\n{e}")

    def _on_select(self, _evt=None) -> None:
        sel = self.tree.selection()
        if not sel:
            return
        alert_id = int(sel[0])

        try:
            alerts = self.svc.get_open_alerts()
            alert = next((a for a in alerts if int(a.get("id") or 0) == alert_id), None)
            if not alert:
                self._set_details("Alert not found (refresh?)")
                return
            notes = alert.get("notes") or "No details available."
            self._set_details(notes)
        except Exception as e:
            self._set_details(f"Failed to load details: {e}")

    def _set_details(self, text: str) -> None:
        self.details.configure(state="normal")
        self.details.delete("1.0", "end")
        self.details.insert("1.0", text)
        self.details.configure(state="disabled")

    @staticmethod
    def _fmt_money(v: Any) -> str:
        try:
            if v is None:
                return ""
            f = float(v)
            return f"${f:.2f}"
        except Exception:
            return ""

    @staticmethod
    def _fmt_pct(v: Any) -> str:
        try:
            if v is None:
                return ""
            f = float(v)
            return f"{f:.0f}%"
        except Exception:
            return ""
